language: node_js
node_js:
  - "0.12"
jdk: oraclejdk8
sudo: true
before_install: npm install -g grunt-cli
install:
  - npm install
  - bower install
before_script: grunt build
script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
  - java -version
  - npm test
  - mvn test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

